Models/Sentence.cs
using System.ComponentModel.DataAnnotations;

namespace MyDictionary.Models
{
    public class Sentence
    {
        /// <summary>
        /// Идентификатор предложения
        /// </summary>
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Предложение на русском языке
        /// </summary>
        [Required(ErrorMessage = "Введите предложение на русском языке")]
        [Display(Name = "Предложение на русском языке")]
        [StringLength(200, ErrorMessage = "Предложение не должно содержать более 200 символов")]
        public string RusValue { get; set; } = null!;

        /// <summary>
        /// Предложение на анлийском языке
        /// </summary>
        [Required(ErrorMessage = "Введите предложение на английском языке")]
        [Display(Name = "Предложение на анлийском языке")]
        [StringLength(200, ErrorMessage = "Предложение не должно содержать более 200 символов")]
        public string EngValue { get; set; } = null!;

        /// <summary>
        /// Вид времени английского языка
        /// </summary>
        [Required(ErrorMessage = "Введите вид времени английского языка")]
        [Display(Name = "Вид времени английского языка")]
        public Tences Tense {  get; set; } 

        public Sentence() { }
    }
}

ViewModels/CheckSentencesViewModel.cs
using MyDictionary.Models;

namespace MyDictionary.ViewModels
{
    public class CheckSentencesViewModel
    {
        /// <summary>
        /// Рандомно выбранное предложение
        /// </summary>
        public Sentence RandomSentence { get; set; } = null!;

        /// <summary>
        /// Количество всех ответов
        /// </summary>
        public int AllQuestionsNumber { get; set; }

        /// <summary>
        /// Количество правильных ответов
        /// </summary>
        public int GoodAnswersNumber { get; set; }

        /// <summary>
        /// Количество неправильных ответов
        /// </summary>
        public int BadAnswersNumber { get; set; }

        /// <summary>
        /// Словесная оценка пользователя за его ответ
        /// </summary>
        public string Grades { get; set; } = "";

        public CheckSentencesViewModel(Sentence sentence) 
        {
            RandomSentence = sentence;
        }

        public CheckSentencesViewModel(Sentence sentence, int allQuestion, int goodAnswers, int badAnswers, string grades, string mark) 
        {
            RandomSentence = sentence;
            AllQuestionsNumber = allQuestion;
            GoodAnswersNumber = goodAnswers;
            BadAnswersNumber = badAnswers;
            Grades = grades;

            AllQuestionsNumber++;
            if (mark == "good")
            {
                GoodAnswersNumber++;
                Grades = "Good job!!!";
            }
            else if (mark == "bad")
            {
                BadAnswersNumber++;
                Grades = "Bad, very bad!!!";
            }
        }
    }
}

Controllers/SentenceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyDictionary.DBContext;
using MyDictionary.Interfaces;
using MyDictionary.Models;
using MyDictionary.ViewModels;
using System.Text.Json;

namespace MyDictionary.Controllers
{
    public class SentenceController : Controller
    {
        private readonly ISentenceInterface _sentences;
        private readonly WordsDbContext _dbContext;

        public SentenceController(ISentenceInterface sentences, WordsDbContext dbContext)
        {
            _sentences = sentences;
            _dbContext = dbContext;
        }

        /// <summary>
        /// Метод создания предложения
        /// </summary>
        /// <returns></returns>
        public IActionResult CreateSentence()
        {
            var sentence = new Sentence();

            return View("EditSentence", sentence);
        }

        /// <summary>
        /// Метод редактирования предложения по его id
        /// </summary>
        /// <param name="sentencedId">id предложения</param>
        /// <returns></returns>
        public IActionResult EditSentence(int sentenceId)
        {
            var sentence = _sentences.GetSentenceById(sentenceId);

            // TODO: create view EditSentence
            return View(sentence);
        }

        /// <summary>
        /// Метод удаления предложения по его id
        /// </summary>
        /// <param name="sentenceId">id предложения</param>
        /// <returns></returns>
        public IActionResult DeleteSentence(int sentenceId)
        {
            var sentence = _sentences.GetSentenceById(sentenceId);
            _dbContext.Sentences.Remove(sentence);
            _dbContext.SaveChanges();

            return View("SuccessDelete", sentence);
        }

        /// <summary>
        /// Метод рандомного выбора и проверки предложений
        /// </summary>
        /// <returns></returns>
        public IActionResult CheckSentences()
        {
            try
            {
                // получаем времена англ.языка либо по выбору пользователя, либо по дефолту
                var defoultEnglishTences = "[\"PresentSimple\",\"PastSimple\",\"FutureSimple\"]";

                var tencesJson = HttpContext.Session.GetString("listTences") ?? defoultEnglishTences;
                var tences = JsonSerializer.Deserialize<List<string>>(tencesJson);

                var randomSentence = _sentences.GetRandomSentence(tences);

                var viewModel = new CheckSentencesViewModel(randomSentence);

                return View(viewModel);
            }
            catch (Exception error)
            {
                var errorViewModel = new ErrorViewModel(error.Message);
                return View("Error", errorViewModel);
            }
        }

        [HttpPost]
        public IActionResult CheckSentences(int allQuestion, int goodAnswers, int badAnswers, string grades, string mark)
        {
            try
            {
                // получаем времена англ.языка либо по выбору пользователя, либо по дефолту
                var defoultEnglishTences = "[\"PresentSimple\",\"PastSimple\",\"FutureSimple\"]";

                var tencesJson = HttpContext.Session.GetString("listTences") ?? defoultEnglishTences;
                var tences = JsonSerializer.Deserialize<List<string>>(tencesJson);

                var randomSentence = _sentences.GetRandomSentence(tences);

                var viewModel = new CheckSentencesViewModel(randomSentence, allQuestion, goodAnswers, badAnswers, grades, mark);

                return View(viewModel);
            }
            catch (Exception error)
            {
                var errorViewModel = new ErrorViewModel(error.Message);
                return View("Error", errorViewModel);
            }
        }

        /// <summary>
        /// Метод вывода списка предложений по запросу
        /// </summary>
        /// <param name="viewModel">вьюмодель для запроса предложений</param>
        /// <returns></returns>
        public IActionResult GetSentencesQueryResult(EditItemsViewModel viewModel)
        {
            var listSentences = new List<Sentence>();
            listSentences = _dbContext.Sentences.Where(x =>
                    (x.RusValue.Contains(viewModel.RusValue) ||
                     x.EngValue.Contains(viewModel.EngValue))).ToList();

            return View(listSentences);
        }

        /// <summary>
        /// Метод сохранения предложения
        /// </summary>
        /// <param name="sentence">сохраняемое предложение</param>
        /// <param name="formValues">данные полей ввода из формы ввода</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult SaveSentence(Sentence sentence, IFormCollection formValues)
        {
            try
            {
                if (sentence != null && sentence.Id == 0)
                {
                    _dbContext.Sentences.Add(sentence);
                    _dbContext.SaveChanges();
                    return View("Success", sentence);
                }
                else if (sentence != null && sentence.Id != 0)
                {
                    _dbContext.Entry(sentence).State = EntityState.Modified;
                    _dbContext.SaveChanges();
                    return View("Success", sentence);
                }
                return View("EditSentence", sentence);
            }
            catch (Exception error)
            {
                var errorViewModel = new ErrorViewModel(error.Message);
                return View("Error", errorViewModel);
            }
        }
    }
}

Views/Sentence/CheckSentences.cshtml
@model CheckSentencesViewModel;

<div class="homePage">

    @await Html.PartialAsync("HomeButtonPartial")

    <div class="homeHeader">

        <h1 class="title">My dictionary</h1>
        <hr class="horizontal-line" /><br />

        <div class="displayFlex">
            <div class="col-3 col-12-medium flexColumn">
                <div class="card inline">
                    <span>
                        <p>@Model.RandomSentence.RusValue</p>
                    </span>
                </div>
                <div class="info-box-left inline">
                    <div class="info-block">
                        <p>Index: </p>
                        <p>Время английского языка: @Model.RandomSentence.Tense</p>
                    </div>

                </div>
            </div>

            <div class="col-8 col-12-medium marginLeft3">

                <form method="post">
                    <div id="blurElement" class="cardBlur" onclick="disBlur()">
                        <div class="card leftPadCard">
                            @Model.RandomSentence.EngValue
                        </div>
                    </div>
                    <div class="inCenter">
                        <input type="submit" class="nextWord" 
                            asp-controller="Sentence" asp-action="CheckSentences"
                            asp-route-allQuestion="@Model.AllQuestionsNumber" 
                            asp-route-goodAnswers="@Model.GoodAnswersNumber" 
                            asp-route-badAnswers="@Model.BadAnswersNumber"
                            asp-route-grades="@Model.Grades" 
                            asp-route-mark="good" value="correct answer" />
                        <span class="betweenButtons"></span>
                        <input type="submit" class="nextWord" 
                            asp-controller="Sentence" asp-action="CheckSentences"
                            asp-route-allQuestion="@Model.AllQuestionsNumber" 
                            asp-route-goodAnswers="@Model.GoodAnswersNumber" 
                            asp-route-badAnswers="@Model.BadAnswersNumber"
                            asp-route-grades="@Model.Grades" 
                            asp-route-mark="bad" value="uncorrect answer" />
                    </div>
                    @{
                        var goodMarksLevel = 0.0m;
                        var badMarksLevel = 0.0m;

                        if (Model.AllQuestionsNumber != 0)
                        {
                            goodMarksLevel = Math.Round((Model.GoodAnswersNumber * 100.0m / Model.AllQuestionsNumber), 2);
                            badMarksLevel = Math.Round((Model.BadAnswersNumber * 100.0m / Model.AllQuestionsNumber), 2);
                        }
                    }
                    <div class="info-box-right2">
                        <div class="grades-block">
                            <div>Оценка:</div>
                            <div class="grades">@Model.Grades</div>
                        </div>
                        <div class="flexRow space-between statistic-block">
                            <div><p>Всего вопросов: @Model.AllQuestionsNumber</p></div>
                            <div>
                                <p>Правильно: @Model.GoodAnswersNumber (@goodMarksLevel %)</p>
                            </div>
                            <div>
                                <p>Не правильно: @Model.BadAnswersNumber (@badMarksLevel %)</p>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    function disBlur(){
        let element = document.getElementById("blurElement");
        element.style.filter = "blur(0)";
    }
</script>

Views/Sentence/EditSentence.cshtml
@model Sentence

<div class="editPage">

    @await Html.PartialAsync("EditButtonPartial")

    <div class="editHeader">

        <h1 class="title">Create, edit, delete sentences</h1>
        <hr class="horizontal-line" />

        <div class="displayFlex2">
            <div class="flexColumn">

                <form asp-controller="Sentence" asp-action="SaveSentence" method="post">
                    <input type="hidden" asp-for="Id" />

                    <div asp-validation-summary="All"></div>
                    <div class="card">
                        <label asp-for="EngValue"></label>
                        <input type="text" asp-for="EngValue" />
                        <span asp-validation-for="EngValue"></span>
                    </div>
                    <div class="card">
                        <label asp-for="RusValue"></label>
                        <input type="text" asp-for="RusValue" />
                        <span asp-validation-for="RusValue"></span>
                    </div>
                    <div class="edit-box-left inline">
                        <label asp-for="Tense"></label>
                        <select asp-for="Tense"
                                asp-items="Html.GetEnumSelectList<Tences>()">
                        </select>
                        <span asp-validation-for="Tense"></span>
                    </div>
                    <div class="card">
                        <input type="submit" class="submitButton" id="submit" value="Сохранить" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Sentence/GetSentencesQueryResult.cshtml
@model List<Sentence>
<div class="editPage">

    @await Html.PartialAsync("EditButtonPartial")

    <div class="editHeader">

        <h2 class="title">Результаты поиска: </h2>
        <hr class="horizontal-line" />

        @foreach (var item in Model)
        {
            <div class="card">
                <div>
                    <h4>Id: @item.Id  Время англ. языка: @item.Tense.ToString()</h4>
                </div>
                <div>
                    <h3>@item.EngValue</h3>
                </div>
                <div>
                    <h3>@item.RusValue</h3>
                </div>
                <div class="editDelete">
                    <a asp-controller="Sentence" asp-action="EditSentence" asp-route-sentenceId="@item.Id">редактировать</a>
                    <a asp-controller="Sentence" asp-action="DeleteSentence" asp-route-sentenceId="@item.Id">удалить</a>
                </div>
            </div>
        }
    </div>
</div>