Controllers/EditController.cs
using Microsoft.AspNetCore.Mvc;
using MyDictionary.Models;
using MyDictionary.ViewModels;

namespace MyDictionary.Controllers
{
    public class EditController : Controller
    {
        /// <summary>
        /// Метод вывода страницы ввода, редактирования, удаления слов / предложений / грамматики
        /// </summary>
        /// <returns></returns>
        public IActionResult Index(string type = "Word")
        {
            var model = new EditItemsViewModel(type);

            return View(model);
        }

    }
}

Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyDictionary.Controllers
{
    public class TaskController : Controller
    {
        /// <summary>
        /// Метод вывода общих задач
        /// </summary>
        /// <returns></returns>
        public IActionResult CommonTask()
        {
            return View();
        }

        /// <summary>
        /// Метод вывода задач страницы Home
        /// </summary>
        /// <returns></returns>
        public IActionResult HomeTask()
        {
            return View();
        }

        /// <summary>
        /// Метод вывода задач страницы Edit
        /// </summary>
        /// <returns></returns>
        public IActionResult EditTask()
        {
            return View();
        }
    }
}

Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/ckeditor5/ckeditor5-content.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/ckeditor5/ckeditor5-editor.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/ckeditor5/ckeditor5.css" asp-append-version="true" />

Views/Shared/EditButtonPartial.cshtml
<div class="editButton">
    <a asp-controller="Edit" asp-action="Index" asp-route-type="Word">Редактировать слова</a>
    <a asp-controller="Edit" asp-action="Index" asp-route-type="Sentence">Редактировать предложения</a>
    <a asp-controller="Edit" asp-action="Index" asp-route-type="Grammar">Редактировать грамматику</a>
</div>

Views/Shared/FooterPartial.cshtml
<footer>
    <div id="footer-wrapper">
        &copy; 2024 - MyDictionary - 
        // <a asp-area="" asp-controller="Home" asp-action="Index">Home Page</a> // 
        <a asp-area="" asp-controller="Home" asp-action="Edit">Edit Page</a> //
    </div>
</footer>

Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
	<div class="container">
		<div class="row">
			<div class="col-12">

				<header id="header">
					<h1><a asp-controller="Home" asp-action="Index" id="logo">MyDictionary</a></h1>
					<nav id="nav">
						<a asp-controller="Home" asp-action="Index">Главная</a>
						<a asp-controller="Edit" asp-action="Index">Edit</a>
						<a asp-controller="Task" asp-action="CommonTask">CommonTask</a>
						<a asp-controller="Task" asp-action="HomeTask">HomeTask</a>
						<a asp-controller="Task" asp-action="EditTask">EditTask</a>
					</nav>
				</header>
			</div>
		</div>
	</div>
</div>

Views/Shared/HomeButtonPartial.cshtml
<div class="homeButton">
    <div class="homeButtonLink">
        <a asp-controller="Word" asp-action="CheckWords">Проверить слова</a>
    </div>
    <div class="homeButtonLink">
        <a asp-controller="Sentence" asp-action="CheckSentences">Проверить предложения</a>
    </div>
    <div class="homeButtonLink">
        <a asp-controller="Grammar" asp-action="CheckGrammar">Проверить грамматику</a>
    </div>
</div>

Views/Shared/MetaPartial.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyDictionary</title>
</head>

Views/Shared/ScriptPartial.cshtml
<!-- sdn версии js файлов
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->

<script src="~/js/jquery/jquery.min.js"></script>
<script src="~/js/popper/popper.min.js"></script>
<script src="~/js/bootstrap/bootstrap.min.js"></script>

Views/Shared/SidePartial.cshtml
<div class="asidePage">
    <h2>Полезные ссылки:</h2>

    <div>
        <a href="tel:1111111" target="_blank">
            <img src="~/images/SideBar/Dial.bmp" alt="Позвонить" width="24" height="24">
            <h4>Позвонить</h4>
        </a>
    </div>
    <div>
        <a href="mailto:fio@gmail.com" target="_blank">
            <img src="~/images/SideBar/Question.bmp" alt="Задать вопрос" width="24" height="24">
            <h4>Задать вопрос</h4>
        </a>
    </div>
    <div>
        <a href="https://firma@gmail.com" target="_blank">
            <img src="~/images/SideBar/Calculator.bmp" alt="Посчитать тур:" width="24" height="24">
            <h4>Посчитать тур</h4>
        </a>
    </div>
    <br />
    <h2>Мы в соцсетях:</h2>
    <div>
        <a href="https://" target="_blank">
            <img src="~/images/SideBar/Facebook.png" alt="Facebook" width="24" height="24">
            <h4>Facebook</h4>
        </a>
    </div>
    <div>
        <a href="https://" target="_blank">
            <img src="~/images/SideBar/Whatsapp.png" alt="Instagram" width="24" height="24">
            <h4>WhatsApp</h4>
        </a>
    </div>
    <div>
        <a href="https://" target="_blank">
            <img src="~/images/SideBar/Telegram.png" alt="Telegram" width="24" height="24">
            <h4>Telegram</h4>
        </a>
    </div>
    <div>
        <a href="https://" target="_blank">
            <img src="~/images/SideBar/Viber.png" alt="Viber" width="24" height="24">
            <h4>Viber</h4>
        </a>
    </div>
    <br />
    <h2>Feedback:</h2>
    <div>
        <a asp-controller="About" asp-action="FeedBackForm">
            <img src="~/images/SideBar/Email.jpg" alt="Feedback" width="24" height="24">
            <h4>Feedback</h4>
        </a>
    </div>
</div>

Views/Shared/Success.cshtml
<div class="editPage">

    @if (Model.ToString().Contains("Word"))
    {
        @await Html.PartialAsync("EditButtonPartial")

        <div class="editHeader">

            <h3 class="title">Сохранение объекта прошло  успешно!</h3>
            <h4 class="title">Данные сохраненного объекта:</h4>
            <hr class="horizontal-line" />
            <br />
            <div>

                <div class="displayFlex">
                    Id: @Model.Id
                </div>
                <div class="displayFlex">
                    Англ: @Model.EngValue || Рус: @Model.RusValue
                </div>
                <div class="displayFlex">
                    Транскрипция: [ @Model.Transcription ]
                </div>
                <div class="displayFlex">
                    Часть речи: @Model.PartOfSpeech
                </div>
            </div>
        </div>
    }
</div>

Views/Shared/SuccessDelete.cshtml
<div class="editPage">

    @if (Model.ToString().Contains("Word"))
    {
        @await Html.PartialAsync("EditButtonPartial")

        <div class="editHeader">

            <h3 class="title">Удаление объекта прошло  успешно!</h3>
            <h4 class="title">Данные удаленного объекта:</h4>
            <hr class="horizontal-line" />
            <br />
            <div>

                <div class="displayFlex">
                    Id: @Model.Id
                </div>
                <div class="displayFlex">
                    Англ: @Model.EngValue || Рус: @Model.RusValue
                </div>
                <div class="displayFlex">
                    Транскрипция: [ @Model.Transcription ]
                </div>
                <div class="displayFlex">
                    Часть речи: @Model.PartOfSpeech.ToString()
                </div>
            </div>
        </div>
    }
    @if (Model.ToString().Contains("Sentence"))
    {
        @await Html.PartialAsync("EditButtonPartial")

        <div class="editHeader">

            <h3 class="title">Удаление объекта прошло  успешно!</h3>
            <h4 class="title">Данные удаленного объекта:</h4>
            <hr class="horizontal-line" />
            <br />
            <div>

                <div class="displayFlex">
                    Id: @Model.Id
                </div>
                <div class="displayFlex">
                    Англ: @Model.EngValue
                </div>
                <div class="displayFlex">
                    Рус: @Model.RusValue
                </div>
                <div class="displayFlex">
                    Время англ. языка: @Model.Tense.ToString()
                </div>
            </div>
        </div>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @await Html.PartialAsync("MetaPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    
    <div id="page-wrapper">
        @await Html.PartialAsync("HeaderPartial")
        <div id="main" >
            <div class="container palms">
                <div class="row main-row">
                    <div class="col-10 col-12-medium">
                        @RenderBody()
                    </div>
                    <div class="col-2 col-12-medium">
                        @await Html.PartialAsync("SidePartial")
                    </div>
                    @await Html.PartialAsync("FooterPartial")
                </div>
                
            </div>
        </div>
    </div>

    @await Html.PartialAsync("ScriptPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>