Models/Word.cs
using System.ComponentModel.DataAnnotations;

namespace MyDictionary.Models
{
    public class Word
    {
        /// <summary>
        /// Идентификатор слова
        /// </summary>
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Слово на русском языке
        /// </summary>
        [Required(ErrorMessage = "Введите слово на русском языке")]
        [Display(Name = "Слово на русском языке")]
        [StringLength(30, ErrorMessage = "Слово не должно содержать более 30 символов")]
        public string RusValue { get; set; } = null!;

        /// <summary>
        /// Слово на английском языке
        /// </summary>
        [Required(ErrorMessage = "Введите слово на английском языке")]
        [Display(Name = "Слово на английском языке")]
        [StringLength(30, ErrorMessage = "Слово не должно содержать более 30 символов")]
        public string EngValue { get; set; } = null!;

        /// <summary>
        /// Транскрипция
        /// </summary>
        [Display(Name = "Транскрипция")]
        [StringLength(20, ErrorMessage = "Транскрипция не должна содержать более 20 символов")]
        public string? Transcription { get; set; }

        /// <summary>
        /// Часть речи
        /// </summary>
        [Required(ErrorMessage = "Введите часть речи")]
        [Display(Name = "Часть речи")]
        public PartsOfSpeech PartOfSpeech { get; set; } 

        public Word() { }

    }
}

ViewModels/CheckWordsViewModel.cs
using MyDictionary.Models;

namespace MyDictionary.ViewModels
{
    public class CheckWordsViewModel
    {
        /// <summary>
        /// Индекс выбранного слова из коллекции слов
        /// </summary>
        public int IndexOfCheckedWord { get; set; }

        /// <summary>
        /// Рандомно созданная коллекция слов
        /// </summary>
        public List<Word> RandomWords { get; set; } = new List<Word>();

        /// <summary>
        /// Количество вариантов для перевода слова
        /// </summary>
        private int NumberOfWords { get; set; } = 5;

        /// <summary>
        /// Количество всех ответов
        /// </summary>
        public int AllQuestionsNumber { get; set; }

        /// <summary>
        /// Количество правильных ответов
        /// </summary>
        public int GoodAnswersNumber { get; set; }

        /// <summary>
        /// Количество неправильных ответов
        /// </summary>
        public int BadAnswersNumber { get; set; }

        /// <summary>
        /// Словесная оценка пользователя за его ответ
        /// </summary>
        public string Grades { get; set; } = "";

        public CheckWordsViewModel() { }

        /// <summary>
        /// Метод получения количества слов в коллекции - для количества вариантов ответа 
        /// </summary>
        /// <returns></returns>
        public int GetNumberOfWords()
        {
            return this.NumberOfWords;
        }

        public CheckWordsViewModel(List<Word> randomWords, int indexOfCheckedWord)
        {
            RandomWords = randomWords;
            IndexOfCheckedWord = indexOfCheckedWord;
        }

        public CheckWordsViewModel(List<Word> randomWords, int indexOfCheckedWord, int idWord, int allQuestion, int goodAnswers, int badAnswers, string grades, int idSelectedAnswer) : this(randomWords, indexOfCheckedWord)
        {
            IndexOfCheckedWord = idWord;
            AllQuestionsNumber = allQuestion;
            GoodAnswersNumber = goodAnswers;
            BadAnswersNumber = badAnswers;
            Grades = grades;

            AllQuestionsNumber++;

            if (idSelectedAnswer == idWord)
            {
                GoodAnswersNumber++;
                Grades = "Good job!!!";
            }
            else
            {
                BadAnswersNumber++;
                Grades = "Bad, very bad!!!";
            }

            RandomWords = randomWords;
            IndexOfCheckedWord = indexOfCheckedWord;
        }
    }
}

Controllers/WordController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyDictionary.DBContext;
using MyDictionary.Interfaces;
using MyDictionary.Models;
using MyDictionary.Utils;
using MyDictionary.ViewModels;
using System.Text.Json;

namespace MyDictionary.Controllers
{
    public class WordController : Controller
    {
        private readonly IWordsInterface _words;
        private readonly WordsDbContext _dbContext;

        public WordController(IWordsInterface words, WordsDbContext dbContext) 
        {
            _words = words;
            _dbContext = dbContext;
        }

        /// <summary>
        /// Метод создания слова
        /// </summary>
        /// <returns></returns>
        public IActionResult CreateWord()
        {
            var word = new Word();
           
            return View("EditWord", word);
        }

        /// <summary>
        /// Метод редактирования слова по его id
        /// </summary>
        /// <param name="wordId">id слова</param>
        /// <returns></returns>
        public IActionResult EditWord(int wordId)
        {
            var word = _words.GetWordById(wordId);

            return View(word);
        }

        /// <summary>
        /// Метод удаления слова по его id
        /// </summary>
        /// <param name="wordId">id слова</param>
        /// <returns></returns>
        public IActionResult DeleteWord(int wordId) 
        {
            var word = _words.GetWordById(wordId);
            _dbContext.Words.Remove(word);
            _dbContext.SaveChanges();

            return View("SuccessDelete", word);
        }

        /// <summary>
        /// Метод рандомного выбора и проверки слов
        /// </summary>
        /// <returns></returns>
        public IActionResult CheckWords()
        {
            try
            {
                // получаем части речи либо по выбору пользователя, либо по дефолту
                var defoultPartOfSpeech = "[\"Noun\",\"Verb\",\"Adjective\",\"Adverb\"]";

                var partSpeechJson = HttpContext.Session.GetString("listPartOfSpeech") ?? defoultPartOfSpeech;
                var partSpeech = JsonSerializer.Deserialize<List<string>>(partSpeechJson);

                var randomWords = _words.GetRandomWords(partSpeech);

                var indexOfCheckedWord = WordsUtils.GetIndexCheckedWord(randomWords);

                var viewModel = new CheckWordsViewModel(randomWords, indexOfCheckedWord);

                return View(viewModel);
            }
            catch (Exception error)
            {
                var errorViewModel = new ErrorViewModel(error.Message);
                return View("Error", errorViewModel);
            }
        }

        /// <summary>
        /// Метод рандомного выбора и проверки слов (POST версия)
        /// </summary>
        /// <param name="idWord">индекс слова, кот. будет проверяться на правильный перевод</param>
        /// <param name="allQuestion">количество переведенных слов</param>
        /// <param name="goodAnswers">количество правильных ответов</param>
        /// <param name="badAnswers">количество неправильных ответо</param>
        /// <param name="grades">описание оценки</param>
        /// <param name="idSelectedAnswer">индекс слова - одного из многих вариантов перевода</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult CheckWords(int idWord, int allQuestion, int goodAnswers, int badAnswers, string grades, int idSelectedAnswer)
        {
            try
            {
                // при нажатии на кнопку с вариантом ответа б. сгенерированы и отрендерены новые данные для списка слов и индекса выбранного слова (применятся в конце)
                // получаем части речи либо по выбору пользователя, либо по дефолту
                var defoultPartOfSpeech = "[\"Noun\",\"Verb\",\"Adjective\",\"Adverb\"]";

                var partSpeechJson = HttpContext.Session.GetString("listPartOfSpeech") ?? defoultPartOfSpeech;
                var partSpeech = JsonSerializer.Deserialize<List<string>>(partSpeechJson);

                var newRandomWords = _words.GetRandomWords(partSpeech);
                var newIndexOfCheckedWord = WordsUtils.GetIndexCheckedWord(newRandomWords);

                var viewModel = new CheckWordsViewModel(newRandomWords, newIndexOfCheckedWord, idWord, allQuestion, goodAnswers, badAnswers, grades, idSelectedAnswer);

                return View(viewModel);
            }
            catch (Exception error)
            {
                var errorViewModel = new ErrorViewModel(error.Message);
                return View("Error", errorViewModel);
            }
        }

        /// <summary>
        /// Метод вывода списка слов по запросу
        /// </summary>
        /// <param name="viewModel">вьюмодель для запроса слов</param>
        /// <returns></returns>
        public IActionResult GetWordsQueryResult(EditItemsViewModel viewModel)
        {
            var listWords = new List<Word>();
            listWords = _dbContext.Words.Where(x => 
                    (x.RusValue.Contains(viewModel.RusValue) || 
                     x.EngValue.Contains(viewModel.EngValue))).ToList();

            return View(listWords);
        }

        /// <summary>
        /// Метод сохранения слова
        /// </summary>
        /// <param name="word">сохраняемое слово</param>
        /// <param name="formValues">данные полей ввода из формы ввода</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult SaveWord(Word word, IFormCollection formValues)
        {
            try
            {
                var transcription = formValues["insertText"].ToString();
                if (transcription != null) word.Transcription = transcription;

                if (word != null && word.Id == 0)
                {
                    _dbContext.Words.Add(word);
                    _dbContext.SaveChanges();
                    return View("Success", word);
                }
                else if(word != null && word.Id != 0)
                {
                    _dbContext.Entry(word).State = EntityState.Modified;
                    _dbContext.SaveChanges();
                    return View("Success", word);  
                }
                return View("EditWord", word);
            }
            catch (Exception error)
            {
                var errorViewModel = new ErrorViewModel(error.Message);
                return View("Error", errorViewModel);
            }
        }

        /// <summary>
        /// метод вывода полной информации о слове
        /// </summary>
        /// <param name="word">слово</param>
        /// <returns></returns>
        public IActionResult WordDetails(int wordId)
        {
            var word = _words.GetWordById(wordId);

            return PartialView("AnswerCardPartial", word);
        }
    }
}

Views/Word/AnswerCardPartial.cshtml
@model Word

<div class="modal fade" id="answerCard" tabindex="-1" role="dialog" aria-labelledby="answerCardLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="answerCardLabel">Выберите часть речи</h5>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="Word" asp-action="CheckWords">
                    <div class="form-group">
                        <label class="formLabel" asp-for="EngValue"></label>
                        <input type="text" asp-for="EngValue"/>
                    </div> 
                    <div class="form-group">
                        <label class="formLabel" asp-for="Transcription"></label>
                        <input type="text" asp-for="Transcription" />
                    </div>
                    <div class="form-group">
                        <label class="formLabel" asp-for="RusValue"></label>
                        <input type="text" asp-for="RusValue" />
                    </div>
                    <div class="form-group">
                        <label class="formLabel" asp-for="PartOfSpeech"></label>
                        <input type="text" asp-for="PartOfSpeech" />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Word/CheckWords.cshtml
@model CheckWordsViewModel;

<div class="homePage">

    @await Html.PartialAsync("HomeButtonPartial")

    <div class="homeHeader">

        <h1 class="title">My dictionary</h1>
        <hr class="horizontal-line" /><br />
        
        <div class="displayFlex">
            <div class="col-3 col-12-medium flexColumn">
                <div class="card inline">
                    <span>
                        <p>@Model.RandomWords.FirstOrDefault(x => x.Id == Model.IndexOfCheckedWord).RusValue</p>
                    </span>
                </div>
                <div class="info-box-left inline">
                    <div class="info-block">
                        <p>Index: @Model.IndexOfCheckedWord</p>
                        <p>Часть речи: @Model.RandomWords.First().PartOfSpeech</p>
                    </div>
                    
                </div>
            </div>
            <div class="col-8 col-12-medium marginLeft3">

                <form method="post">
                    <div class="displayFlexRow wrap">
                        @foreach (var item in Model.RandomWords)
                        {
                            <input type="submit" class="card" asp-controller="Word" 
                            asp-action="CheckWords"
                            asp-route-idWord="@Model.IndexOfCheckedWord"
                            asp-route-allQuestion="@Model.AllQuestionsNumber"
                            asp-route-goodAnswers="@Model.GoodAnswersNumber"
                            asp-route-badAnswers="@Model.BadAnswersNumber"
                            asp-route-grades="@Model.Grades"
                            asp-route-idSelectedAnswer="@item.Id" value="@item.EngValue" />
                        }
                    </div>
                </form>
                <form asp-controller="Word" asp-action="WordDetails"
                          asp-route-wordId="@Model.IndexOfCheckedWord">
                    <div type="button" class="promptDiv"
                            data-toggle="modal"
                            data-target="#answerCard">
                        <h4>Подсказка*</h4>
                    </div>
                </form>
                <!--
                <div class="inCenter">
                    <input type="submit" class="nextWord" asp-controller="" asp-action="" value="Продолжить" />
                </div>
                -->
                @{
                    var goodMarksLevel = 0.0m;
                    var badMarksLevel = 0.0m;

                    if(Model.AllQuestionsNumber != 0)
                    {
                        goodMarksLevel = Math.Round((Model.GoodAnswersNumber * 100.0m / Model.AllQuestionsNumber), 2);
                        badMarksLevel = Math.Round((Model.BadAnswersNumber * 100.0m / Model.AllQuestionsNumber), 2);
                    }
                }
                <div class="info-box-right3">
                    <div class="grades-block">
                        <div>Оценка:</div>
                        <div class="grades">@Model.Grades</div>
                    </div>
                    <div class="flexRow space-between statistic-block">
                        <div><p>Всего вопросов: @Model.AllQuestionsNumber</p></div>
                        <div>
                            <p>Правильно: @Model.GoodAnswersNumber (@goodMarksLevel %)</p>
                        </div>
                        <div>
                            <p>Не правильно: @Model.BadAnswersNumber (@badMarksLevel %)</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@if(Model.IndexOfCheckedWord != 0)
{
    @await Html.PartialAsync("AnswerCardPartial", Model.RandomWords.FirstOrDefault(x => x.Id == Model.IndexOfCheckedWord))
}

Views/Word/EditWord.cshtml
@model Word

<div class="editPage">

    @await Html.PartialAsync("EditButtonPartial")

    <div class="editHeader">

        <h1 class="title">Create, edit, delete words</h1>
        <hr class="horizontal-line" />

        @* для CKEditor 5 *@
        <script src="~/js/ckeditor5/ckeditor5.js"></script>

        <div class="displayFlex2">
            <div class="flexColumn">

                <form asp-controller="Word" asp-action="SaveWord" method="post">
                    <input type="hidden" asp-for="Id" />
                                        
                    <div asp-validation-summary="All"></div>
                    <div class="card">
                        <label asp-for="EngValue"></label>
                        <input type="text" asp-for="EngValue" />
                        <span asp-validation-for="EngValue"></span>
                    </div>
                    <div class="card">
                        <label asp-for="Transcription"></label>
                        <div class="">      <!-- <div class="main-container"> -->
                            <div class="editor-container editor-container_inline-editor" id="editor-container">
                                <div class="editor-container__editor">
                                    <div name="editor" id="editor"></div>
                                </div>
                                <textarea name="insertText" asp-for="Transcription" rows="1" cols="86">
                                    Сюда вставим транскрипцию слова для сохранения модели
                                </textarea>
                            </div>
                        </div>
                        <span asp-validation-for="Transcription"></span>
                    </div>
                    <div class="card">
                        <label asp-for="RusValue"></label>
                        <input type="text" asp-for="RusValue" />
                        <span asp-validation-for="RusValue"></span>                        
                    </div>
                    <div class="edit-box-left inline">
                        <label asp-for="PartOfSpeech"></label>
                        <select asp-for="PartOfSpeech" 
                            asp-items="Html.GetEnumSelectList<PartsOfSpeech>()">
                        </select>
                        <span asp-validation-for="PartOfSpeech"></span>
                    </div>
                    <div class="card">
                        <input type="submit" class="submitButton" id="submit" value="Сохранить" />
                    </div>
                 </form>
            </div>
         </div>
    </div>
</div>
@await Html.PartialAsync("ScriptCkeditorPartial")

Views/Word/GetWordsQueryResult.cshtml
@model List<Word>
<div class="editPage">

    @await Html.PartialAsync("EditButtonPartial")

    <div class="editHeader">

        <h2 class="title">Результаты поиска: </h2>
        <hr class="horizontal-line" />

        @foreach (var item in Model)
        {
            <div class="card">
                <div>
                    <h4>Id: @item.Id  Часть речи: @item.PartOfSpeech.ToString()</h4>
                </div>
                <div>
                    <h3>@item.EngValue [ @item.Transcription ] @item.RusValue</h3>
                </div>
                <div class="editDelete">
                    <a asp-controller="Word" asp-action="EditWord" asp-route-wordId="@item.Id">редактировать</a>
                    <a asp-controller="Word" asp-action="DeleteWord" asp-route-wordId="@item.Id">удалить</a>
                </div>
            </div>
        }
    </div>
</div>

Views/Word/ScriptCkeditorPartial.cshtml
<script type="importmap">
{
    "imports": {
        "ckeditor5": "@Url.Content("~/js/ckeditor5/ckeditor5.js")",
        "ckeditor5/": "@Url.Content("~/js/ckeditor5/")"
    }
}
</script>
<script type="module" src="~/js/main.js"></script>
<script type="module" src="~/js/ckeditor5/ckeditor5.js"></script>